### ISSUE TITLE
这个还有用吗

### ISSUE THREAD

**Issue by 17791843** [ygxiuming/QN-big-study#10]

**Comment by ygxiuming** [comment]
不晓得，你试试呗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月31日(周五) 上午9:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ygxiuming/QN-big-study] 这个还有用吗 (Issue #10)

**Comment by 17791843** [comment]
![20230331120042](https://user-images.githubusercontent.com/122306495/229019606-81e6325f-032d-4794-bb5d-c31621052adb.png)

**Comment by Lasey** [comment]
现在貌似不行了，这几天系统升级咯

**Comment by ygxiuming** [comment]
> 现在貌似不行了，这几天系统升级咯

已修复，但是需要自己填写对应的accesstoken
