### ISSUE TITLE
老页面接口现在还能用嘛，感觉打不上卡了

### ISSUE THREAD

**Issue by WFPeterChen** [ygxiuming/QN-big-study#12]

**Comment by ygxiuming** [comment]
他的服务器崩了，现在还没有修复好，即使你是手动看，也后台没有记录



---原始邮件---
发件人: "CHEN ***@***.***&gt;
发送时间: 2023年7月1日(周六) 中午1:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ygxiuming/QN-big-study] 老页面接口现在还能用嘛，感觉打不上卡了 (Issue #12)

**Comment by WFPeterChen** [comment]
现在需要openid了，大佬能修复一下嘛

**Comment by Zzzz0077** [comment]
作者大大，现在需要绑定微信的accesstoken了，有啥办法能绕过后台验证嘛，管理后台地址：http://106.225.141.143:8103/pub/login，有需要帮忙的随时可以联系我

**Comment by ygxiuming** [comment]
好的，我有时间看看，因为工作了，不经常看，如果确实加了openid的话，要么自己提前获取这个，要么自己模拟生成(一般微信openid是不大可能自己生成的）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月2日(周日) 上午7:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ygxiuming/QN-big-study] 老页面接口现在还能用嘛，感觉打不上卡了 (Issue #12)




 
作者大大，现在需要绑定微信的accesstoken了，有啥办法能绕过后台验证嘛，管理后台地址：http://106.225.141.143:8103/pub/login，有需要帮忙的随时可以联系我

**Comment by ygxiuming** [comment]
已修复，大家测试一下，有问题发我，token目前没时间写，大家自行前往后台，点击  学习记录，然后按F12，进行抓包刷新，可以看到所有已有记录的token

**Comment by Zzzz0077** [comment]
在我们并不知道对方的accesstoken的情况下，这个代码可以进行批量打卡嘛，团委这边可能要打卡的人数比较多

**Comment by ygxiuming** [comment]
不行，但是后台查看记录界面是可以查看到token的，你可以查以往期已打记录，然后在里面找，可以批量获取到他的token，对了，他这里面不叫token，叫userid



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月2日(周日) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ygxiuming/QN-big-study] 老页面接口现在还能用嘛，感觉打不上卡了 (Issue #12)




 
在我们并不知道对方的accesstoken的情况下，这个代码可以进行批量打卡嘛，团委这边可能要打卡的人数比较多

**Comment by ygxiuming** [comment]
每个管理员应该是有查看记录的，账号密码，那个网址我也发了，只要能进后台，他的以往打卡的那个token是可以导出来，后台里面叫做userid



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月2日(周日) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ygxiuming/QN-big-study] 老页面接口现在还能用嘛，感觉打不上卡了 (Issue #12)




 
在我们并不知道对方的accesstoken的情况下，这个代码可以进行批量打卡嘛，团委这边可能要打卡的人数比较多

**Comment by Zzzz0077** [comment]
喔喔喔查到了，有啥办法可以批量的导出这些userid嘛，一个一个的复制太麻烦啦

**Comment by ygxiuming** [comment]
加我微信，我帮你搞，lzming2001



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月2日(周日) 下午3:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ygxiuming/QN-big-study] 老页面接口现在还能用嘛，感觉打不上卡了 (Issue #12)




 
喔喔喔查到了，有啥办法可以批量的导出这些userid嘛，一个一个的复制太麻烦啦

**Comment by ygxiuming** [comment]
维护，没有办法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月4日(周二) 晚上10:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ygxiuming/QN-big-study] 老页面接口现在还能用嘛，感觉打不上卡了 (Issue #12)




 
http://106.225.141.143:8103/
 这个好像崩了
 咋办？
