### ISSUE TITLE
qndxx代码可能更新了

### ISSUE THREAD

**Issue by SSStardust1** [ygxiuming/QN-big-study#14]
学习结果是上一期的青年大学习

**Comment by ygxiuming** [comment]
已经解决

**Comment by 1304009050** [comment]
貌似还是执行结果还是那样，没有做的还是显示上一期的结果，自己做了的显示当前期,后台没有变化。
` 78%|███████▊  | 14/18 [00:06<00:01,  2.19it/s]{"code":"-1","error":true,"msg":"添加失败","state":"error","success":false,"sys
temSwitch":0}`
