### ISSUE TITLE
[ml-day-1]依赖xlrd版本未知

### ISSUE THREAD

**Issue by moyvch** [ygxiuming/QN-big-study#2]
项目环境不完善，xlrd的版本未知，使用xlrd-2.01版运行结果如下
```shell
是否同意以上声明，同意（请输入1），不同意（请输入0） ：1

 1.青年大学习组织id查询
 2.青年大学习开始学习

请输入选择模式序号：2
第22期青年大学习标题：2022年第21期
青年大学习学习链接：https://h5.cyol.com/special/daxuexi/dr9ja2jkc6/index.html
Traceback (most recent call last):
  File "E:\cache\QN-big-study-main\QN-big-study-main\QN_study.py", line 213, in <module>
    QNstudy()
  File "E:\cache\QN-big-study-main\QN-big-study-main\QN_study.py", line 172, in QNstudy
    data_excel = xlrd.open_workbook('名单.xlsx')
  File "C:\Users\0\AppData\Local\Programs\Python\Python39\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
```
希望作者提供xlrd的版本

**Comment by ygxiuming** [comment]
xlrd最新版本-2.0.1不支持读取*.xlsx文件
请使用xlrd ==1.2.0版本运行
pip install xlrd==1.2.0

**Comment by ygxiuming** [comment]
> 项目环境不完善，xlrd的版本未知，使用xlrd-2.01版运行结果如下
> 
> ```shell
> 是否同意以上声明，同意（请输入1），不同意（请输入0） ：1
> 
>  1.青年大学习组织id查询
>  2.青年大学习开始学习
> 
> 请输入选择模式序号：2
> 第22期青年大学习标题：2022年第21期
> 青年大学习学习链接：https://h5.cyol.com/special/daxuexi/dr9ja2jkc6/index.html
> Traceback (most recent call last):
>   File "E:\cache\QN-big-study-main\QN-big-study-main\QN_study.py", line 213, in <module>
>     QNstudy()
>   File "E:\cache\QN-big-study-main\QN-big-study-main\QN_study.py", line 172, in QNstudy
>     data_excel = xlrd.open_workbook('名单.xlsx')
>   File "C:\Users\0\AppData\Local\Programs\Python\Python39\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
>     raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
> xlrd.biffh.XLRDError: Excel xlsx file; not supported
> ```
> 
> 希望作者提供xlrd的版本

xlrd最新版本-2.0.1不支持读取*.xlsx文件
请使用xlrd ==1.2.0版本运行
pip install xlrd==1.2.0
