### ISSUE TITLE
源码

### ISSUE THREAD

**Issue by liuzhongkun1** [ygxiuming/QN-big-study#3]
请问有源码吗

**Comment by ygxiuming** [comment]
额，我不是发在GitHub上了吗？上面就是源码啊发自我的 iPad在 2022年10月18日，20:14，刘锺坤 ***@***.***> 写道：﻿
请问有源码吗

**Comment by liuzhongkun1** [comment]
抱歉抱歉，没看到，ε=(´ο｀*)))唉

**Comment by liuzhongkun1** [comment]
This is an auto vacation reply. Hi, I am so sorry. I may not reply in time. I will reply to you soon when I see it.——lzk
