### ISSUE TITLE
win版学习接口还是29期

### ISSUE THREAD

**Issue by jiangxi-am** [ygxiuming/QN-big-study#9]
您好，这个星期我在测试时发现运行日志为2022年第29期
青年大学习学习链接：https://h5.cyol.com/special/daxuexi/dg1m2kw1e2/index.html；
且在上个星期开始出现生成截图运行会出现闪退状况，其他方式暂未运行，不知是否有同样问题。

**Comment by ygxiuming** [comment]
我刚刚试过了，程序正常运行，没有问题，你再试试，或者你把出错界面截图发我看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月20日(周二) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ygxiuming/QN-big-study] win版学习接口还是29期 (Issue #9)




 
您好，这个星期我在测试时发现运行日志为2022年第29期
 青年大学习学习链接：https://h5.cyol.com/special/daxuexi/dg1m2kw1e2/index.html；
 且在上个星期开始出现生成截图运行会出现闪退状况，其他方式暂未运行，不知是否有同样问题。

**Comment by jiangxi-am** [comment]
以下为使用win服务器复现的问题视频https://clipchamp.com/watch/QbEH0ESNQjM

**Comment by jiangxi-am** [comment]
在win11上生成截图出现闪退问题，更换win2012后测试发现为出现闪退问题，但学习的接口与win11一样仍为29期，在这个星期之前测试学习是正常的。

**Comment by ygxiuming** [comment]
好的，问题我明白了，我下午看看问题出在哪里。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月20日(周二) 中午12:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ygxiuming/QN-big-study] win版学习接口还是29期 (Issue #9)




 
在win11上生成截图出现闪退问题，更换win2012后测试发现为出现闪退问题，但学习的接口与win11一样仍为29期，在这个星期之前测试学习是正常的。

**Comment by jiangxi-am** [comment]
> 好的，问题我明白了，我下午看看问题出在哪里。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年12月20日(周二) 中午12:40 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ygxiuming/QN-big-study] win版学习接口还是29期 (Issue #9) 在win11上生成截图出现闪退问题，更换win2012后测试发现为出现闪退问题，但学习的接口与win11一样仍为29期，在这个星期之前测试学习是正常的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
非常感谢您的回复，期待问题能够解决！

**Comment by ygxiuming** [comment]
> > 好的，问题我明白了，我下午看看问题出在哪里。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年12月20日(周二) 中午12:40 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [ygxiuming/QN-big-study] win版学习接口还是29期 (Issue #9) 在win11上生成截图出现闪退问题，更换win2012后测试发现为出现闪退问题，但学习的接口与win11一样仍为29期，在这个星期之前测试学习是正常的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 非常感谢您的回复，期待问题能够解决！

已更新，在老链接中，你试试

**Comment by jiangxi-am** [comment]
> > > 好的，问题我明白了，我下午看看问题出在哪里。
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年12月20日(周二) 中午12:40 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [ygxiuming/QN-big-study] win版学习接口还是29期 (Issue #9) 在win11上生成截图出现闪退问题，更换win2012后测试发现为出现闪退问题，但学习的接口与win11一样仍为29期，在这个星期之前测试学习是正常的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > > 非常感谢您的回复，期待问题能够解决！
> 
> 已更新，在老链接中，你试试

真是麻烦您了，现已测试能够正常使用，生成截图闪退是我本机问题，重启下电脑重新运行就可以了。
